### ISSUE TITLE
Auto/Type Casting/Conversion

### ISSUE THREAD

**Issue by Tx83** [nicholasdille/PowerShell-Statistics#1]
Hi Nicholas,

Absolutely love this concept and your use of PowerShell - however thought important to mention the following issues;

```
PS C:\> $obj | Measure-Object -Property 'data_z'

Cannot convert value "0.000025400.00002540" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Program Files\WindowsPowerShell\Modules\Statistics\1.1.53\Measure-Object.ps1:59 char:13
+ $Median = ($LowerMedian + $UpperMedian) / 2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastFromStringToInteger
```
It would appear that auto/type casting/conversion in your code has not worked as expected for various input value types (ie. simple JSON structure pulled from an API).

Subsequently, your code concatenates two strings which cannot be divided by 2, the result of this operation fails (as above) throwing exception "InvalidCastFromStringToInteger" later attempting to be stored as the Median property value for the output object of Measure-Object.

The full/modified object [Microsoft.PowerShell.Commands.GenericMeasureInfo] is returned, however without the Median property value populated;

```
Median            :
Variance          : 5.58076226080845E-17
StandardDeviation : 7.47044996021555E-09
Percentile10      : 0.00002360
Percentile25      : 0.00002424
Percentile75      : 0.00002655
Percentile90      : 0.00002788
TukeysRange       : 3.465E-06
Confidence95      : 6.5481381019526E-11
Count             : 5000000
Average           : 2.54548833999973E-05
Sum               : 1.27274416999986
Maximum           : 2.91E-05
Minimum           : 1.854E-05
Property          : data_z
```

Yes, with certainty I can manually re-type/cast/convert or rebuild/cleanse the entire data set/object prior to measurement (requiring more memory and processing time) but this task should however be handled by the function during processing - saving time, resources and is overall a seamless experience for your users.

I suspect this issue may also be prevalent when using Get-Histogram (quick side note: the performance of Get-Histogram is a bit slow and may need a few tweaks when processing values in a large data set).

Also, as demonstrated in your blog;

Piping the result object from Measure-Object of type [GenericMeasureInfo] to Show-Measurement does not appear to be working with described usage:

```
PS C:\> $obj | Measure-Object -Property 'data_z' | Show-Measurement
```

Instead the following usage applies:

```
PS C:\> $m = $obj | Measure-Object -Property 'data_z'
PS C:\> Show-Measurement -InputObject $m
```

For reference;

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Hope this helps!

Regards, Tristan

**Comment by nicholasdille** [comment]
@Tx83 thanks for your feedback. This looks like an attempt at adding to values resulting in concatenating them. I'll fix this in the next few days!

**Comment by nicholasdille** [comment]
I have fixed the blog post but the type casting issue will be released with a few more changes already in the pipeline
